### ISSUE TITLE
Add HubMap Assay Ontology in a general way

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#89] opened 2021-09-23 15:46 UTC
This involves adding Ontologies that are not sourced from .owl files in a general way.

From Jonathan: Also there will be some Ontologies that ingest from identical output format as OWLNETS but no run of code from OWL to that - I think he already has that capability to run a OWL file phase and a ‘next phase’ (my code) but perhaps not an ontology with only the later phase (e.g., HUBMAP_ASSAY ontology will come that way).

BLOCKED: Because we need a good Hubmap Asset Ontology to add.

**Comment by shirey** [comment] 2021-11-09 13:24
Closing, because it is a duplicate of https://github.com/hubmapconsortium/ontology-api/issues/113

**Closed by shirey** 2021-11-09 13:24 UTC
